import fs from 'node:fs';
import path from 'node:path';
import { cargoTripleFor } from './cargoTarget.js';
import { isMtWasm, assertMtRustToolchain, cargoTargetDirFor, cargoBuildInvocation } from './rustMt.js';
import runCargo, { cargoRunner } from './runCargo.js';
import { relPath } from './rustBridgeGen.js';
import writeIfChanged from './writeIfChanged.js';

const SUPER = '_app_super';

// App-local Rust surfaces (imported .rs files) live as rlib bridge crates under
// <project>/.crossbind/rust-bridges/ (written by the bundler transformer on import). They are
// bundled into ONE super staticlib here - a single libstd, so the consumer may safely
// force_load/whole-archive exactly this archive next to keep-symbol-linked Rust packages.
export default function buildAppRustCrates(target, cacheDir, cargoDependencies = null, log = console.log) {
    const root = `${cacheDir}/rust-bridges`;
    if (!fs.existsSync(root)) return [];
    let crates = fs.readdirSync(root, { withFileTypes: true })
        .filter((e) => e.isDirectory() && e.name !== SUPER && fs.existsSync(`${root}/${e.name}/Cargo.toml`))
        .map((e) => e.name);

    // Prune bridges whose source of truth is gone. An app-local surface whose .rs was deleted
    // breaks cargo on the missing #[path] target; a crate_ bridge whose cargoDependencies entry
    // was removed silently keeps dead registrations in every later binary. crate_ pruning only
    // runs when the caller passes the current cargoDependencies - null means "don't judge".
    crates = crates.filter((name) => {
        const dir = `${root}/${name}`;
        const libRs = `${dir}/src/lib.rs`;
        const src = fs.existsSync(libRs) ? fs.readFileSync(libRs, 'utf8') : '';
        const pathMod = src.match(/#\[path = "(.+?)"\]\s*\r?\nmod user;/);
        let stale = false;
        if (pathMod) {
            // #[path] is written relative to the file that carries it, so it has to be resolved
            // against that directory - resolving it against cwd finds nothing and prunes a
            // perfectly live bridge.
            stale = !fs.existsSync(path.resolve(path.dirname(libRs), pathMod[1]));
        } else if (cargoDependencies && name.startsWith('crate_')) {
            stale = !Object.keys(cargoDependencies)
                .some((c) => `crate_${c.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase()}` === name);
        }
        if (stale) {
            fs.rmSync(dir, { recursive: true, force: true });
            log(`crossbind: pruned stale rust bridge '${name}' - its source is gone`);
        }
        return !stale;
    });
    if (crates.length === 0) return [];

    const isMt = isMtWasm(target);
    // The prebuilt sysroots live in the image, so they answer only where the build runs there;
    // only the nightly rebuild needs a nightly toolchain on this machine.
    const sysroot = cargoRunner(target) !== 'LOCAL';
    if (isMt && !sysroot) assertMtRustToolchain();

    const superDir = `${root}/${SUPER}`;
    const manifest = [
        '# Generated by crossbind - do not edit. Bundles every app-local Rust surface.',
        '[package]',
        'name = "crossbind-app-super"',
        'version = "0.0.0"',
        'edition = "2021"',
        '',
        '[lib]',
        'name = "crossbind_app_super"',
        'crate-type = ["staticlib"]',
        '',
        '[dependencies]',
        ...crates.map((c) => `${c.replaceAll('_', '-')}-crossbind-app = { path = "${relPath(superDir, `${root}/${c}`)}" }`),
        '',
        '[profile.release]',
        'panic = "abort"',
        '',
        '[workspace]',
        '',
    ].join('\n');
    const lib = [
        '// Generated by crossbind - do not edit. The underscore uses bundle each bridge rlib (and',
        '// its init-array registrations) into this single staticlib.',
        ...crates.map((c) => `use ${c}_crossbind_app as _;`),
        '',
    ].join('\n');
    writeIfChanged(`${superDir}/Cargo.toml`, manifest);
    writeIfChanged(`${superDir}/src/lib.rs`, lib);

    const triple = cargoTripleFor(target);
    if (!triple) throw new Error(`crossbind: app rust crates do not support platform '${target.platform}/${target.arch}'.`);

    const targetDir = cargoTargetDirFor(superDir, target);
    const { args, rustflags, panic, allowUnstable } = cargoBuildInvocation({
        target,
        triple,
        targetDir,
        manifestPath: `${superDir}/Cargo.toml`,
        sysroot,
    });
    const build = runCargo(args, {
        rustflags, panic, allowUnstable, target,
    });
    if (build.status !== 0) {
        throw new Error(`crossbind: cargo build failed for the app rust super-crate (${triple}${isMt && !sysroot ? ', mt/build-std' : ''}${sysroot ? `, ${isMt ? 'mt' : 'st'} sysroot` : ''})`);
    }
    const libFile = `${targetDir}/${triple}/release/libcrossbind_app_super.a`;
    if (!fs.existsSync(libFile)) throw new Error(`crossbind: expected cargo output ${libFile} not found`);
    return [libFile];
}
