// Pure helpers for -bin packages (contract C): the recipe's `bin` block is the single
// source for the tool map; everything else (json, npmignore, dispatcher) derives from it.

export function validateBinConfig(bin) {
    const tools = bin?.tools ?? {};
    const names = Object.keys(tools);
    if (names.length === 0) throw new Error('crossbind: bin.tools is empty');
    const binaries = names.filter((name) => tools[name].kind === 'binary');
    const multicall = names.filter((name) => tools[name].kind === 'multicall-entry');
    if (multicall.length > 0 && binaries.length !== 1) {
        throw new Error('crossbind: multicall-entry tools need exactly one kind:"binary" host tool');
    }
    return { tools, names, binaries, multicall };
}

export function renderBinJson(bin) {
    return `${JSON.stringify({ tools: bin.tools }, null, 2)}\n`;
}

export function renderBinNpmignore(bin) {
    const published = Object.entries(bin.tools ?? {})
        .filter(([, tool]) => tool.publish)
        .map(([name]) => name);
    return `${[
        '# GENERATED by crossbind from the recipe bin map (crossbind.build.js) - do not edit.',
        '*.xcframework.zip',
        '*.tgz',
        '.crossbind',
        '*.dylib',
        '# bin package: ship only the tools the bin map declares publish:true, plus share/ data.',
        'dist/prebuilt/**/bin/*',
        ...published.map((name) => `!dist/prebuilt/**/bin/${name}`),
        'dist/prebuilt/**/lib',
        'dist/prebuilt/**/include',
        'dist/prebuilt/**/share/man',
        'dist/prebuilt/**/share/doc',
        'dist/prebuilt/**/share/bash-completion',
    ].join('\n')}\n`;
}

// npm command surface: one `<tool>-wasi` shim per shipped tool, all sharing the copied runner.
export function renderBinCommands(bin) {
    if (bin.commands === false) return {};
    return Object.fromEntries(
        Object.entries(bin.tools ?? {})
            .filter(([, tool]) => tool.publish)
            .map(([name]) => [`${name}-wasi`, `bin/${name}-wasi.mjs`]),
    );
}

export function renderCommandStub(tool) {
    return [
        '#!/usr/bin/env node',
        '// GENERATED by crossbind from the recipe bin map (crossbind.build.js) - do not edit.',
        "import { run } from 'crossbind/src/runtime/wasiRun.mjs';",
        '',
        `await run(import.meta.url, '${tool}');`,
        '',
    ].join('\n');
}

export function renderDispatcher(bin) {
    const { binaries, multicall } = validateBinConfig(bin);
    const host = binaries[0];
    const symbolOf = (tool) => `${tool}_multicall_main`;
    return [
        '#include <cstring>',
        ...[host, ...multicall].map((tool) => `int ${symbolOf(tool)}(int, char**);`),
        'int main(int argc, char** argv) {',
        '    const char* tool = argc > 1 ? argv[1] : "";',
        ...multicall.map((tool) => `    if (!std::strcmp(tool, "${tool}")) return ${symbolOf(tool)}(argc - 1, argv + 1);`),
        `    return ${symbolOf(host)}(argc, argv);`,
        '}',
        '',
    ].join('\n');
}
