packages:
  - 'core/*'
  - 'packages/*'
  - 'plugins/*'
  - 'samples/*'
  - 'website'
  - '!samples/cppjs-sample-mobile-reactnative-nativecli'
  - '!samples/cppjs-sample-mobile-reactnative-expo'
  - '!**/test/**'
