packages:
  - 'cppjs-core/*'
  - 'cppjs-plugins/*'
  - 'cppjs-samples/*'
  - '!cppjs-samples/cppjs-sample-mobile-reactnative-expo'
  - 'cppjs-packages/*/*'
  - 'cppjs-extensions/*'
  - 'website'
  - '!**/test/**'
