const fs = require('node:fs');
const path = require('node:path');

// Metro resolves to real files, so the bare `cpp.js` specifier needs one on disk. The placeholder
// content never reaches the bundle: the transformer replaces it with the platform's proxy module.
module.exports = function getRuntimeFile(state) {
    const file = path.join(state.config.paths.cache, 'cppjs-runtime.js');
    if (!fs.existsSync(file)) {
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, '// Generated by cpp.js - replaced per platform at transform time.\n');
    }
    return file;
};
