import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import { cargoTripleFor } from './cargoTarget.js';

const SUPER = '_app_super';

// App-local Rust surfaces (imported .rs files) live as rlib bridge crates under
// <project>/.cppjs/rust-bridges/ (written by the bundler transformer on import). They are
// bundled into ONE super staticlib here - a single libstd, so the consumer may safely
// force_load/whole-archive exactly this archive next to keep-symbol-linked Rust packages.
export default function buildAppRustCrates(target, cacheDir) {
    const root = `${cacheDir}/rust-bridges`;
    if (!fs.existsSync(root)) return [];
    const crates = fs.readdirSync(root, { withFileTypes: true })
        .filter((e) => e.isDirectory() && e.name !== SUPER && fs.existsSync(`${root}/${e.name}/Cargo.toml`))
        .map((e) => e.name);
    if (crates.length === 0) return [];

    const superDir = `${root}/${SUPER}`;
    const manifest = [
        '# Generated by cpp.js - do not edit. Bundles every app-local Rust surface.',
        '[package]',
        'name = "cppjs-app-super"',
        'version = "0.0.0"',
        'edition = "2021"',
        '',
        '[lib]',
        'name = "cppjs_app_super"',
        'crate-type = ["staticlib"]',
        '',
        '[dependencies]',
        ...crates.map((c) => `${c.replaceAll('_', '-')}-cppjs-app = { path = "${root}/${c}" }`),
        '',
        '[profile.release]',
        'panic = "abort"',
        '',
        '[workspace]',
        '',
    ].join('\n');
    const lib = [
        '// Generated by cpp.js - do not edit. The underscore uses bundle each bridge rlib (and',
        '// its init-array registrations) into this single staticlib.',
        ...crates.map((c) => `use ${c}_cppjs_app as _;`),
        '',
    ].join('\n');
    writeIfChanged(`${superDir}/Cargo.toml`, manifest);
    writeIfChanged(`${superDir}/src/lib.rs`, lib);

    const triple = cargoTripleFor(target);
    if (!triple) throw new Error(`cppjs: app rust crates do not support platform '${target.platform}/${target.arch}'.`);

    const build = spawnSync('cargo', [
        'build', '--release', '--target', triple, '--manifest-path', `${superDir}/Cargo.toml`,
    ], { stdio: 'inherit' });
    if (build.status !== 0) {
        throw new Error(`cppjs: cargo build failed for the app rust super-crate (${triple})`);
    }
    const libFile = `${superDir}/target/${triple}/release/libcppjs_app_super.a`;
    if (!fs.existsSync(libFile)) throw new Error(`cppjs: expected cargo output ${libFile} not found`);
    return [libFile];
}

function writeIfChanged(file, content) {
    if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return;
    fs.mkdirSync(file.substring(0, file.lastIndexOf('/')), { recursive: true });
    fs.writeFileSync(file, content);
}
