import spdxParse from 'spdx-expression-parse';

const COPYLEFT_PATTERN = /\b(AGPL|LGPL|GPL|MPL|EPL|EUPL|CDDL)\b/i;

export function isCopyleft(expression) {
    return COPYLEFT_PATTERN.test(expression || '');
}

export function validateSpdx(expression) {
    if (!expression || typeof expression !== 'string') {
        return { isValid: false, error: 'missing license field' };
    }
    try {
        spdxParse(expression);
        return { isValid: true };
    } catch (e) {
        return { isValid: false, error: e.message };
    }
}

export function formatNoticeSections(rows) {
    return [...rows]
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((row) => {
            const lines = [`## ${row.name}${row.license ? ` — ${row.license}` : ''}`, ''];
            if (row.npmName) lines.push(`- package: ${row.npmName}${row.version ? `@${row.version}` : ''}`);
            if (row.nativeVersion) lines.push(`- native version: ${row.nativeVersion}`);
            if (row.sourceUrl) lines.push(`- source: ${row.sourceUrl}${row.sha256 ? ` (sha256: ${row.sha256})` : ''}`);
            if (row.licenseSelected) lines.push(`- license election: ${row.licenseSelected} (declared: ${row.licenseDeclared})`);
            else if (/\bOR\b/.test(row.license || '')) lines.push(`- no license election recorded; the declared expression applies${row.licenseText ? ' and all texts are included' : ' (texts linked above)'}`);
            if (row.licenseNotes) lines.push(`- note: ${row.licenseNotes}`);
            if (row.licenseText) lines.push('', '```', row.licenseText.trim(), '```');
            return lines.join('\n');
        });
}

export function formatNoticesMarkdown(rows) {
    const sections = formatNoticeSections(rows);

    return [
        '# Third-Party Notices',
        '',
        'GENERATED by `cppjs licenses` from recipe metadata (contract D/E) - do not edit.',
        '',
        'This artifact bundles the following native libraries through cpp.js packages.',
        '',
        sections.join('\n\n'),
        '',
    ].join('\n');
}

// K4 companion: a -bin artifact statically links every row, so its npm license
// field is the AND of all effective component licenses - derived, never typed.
export function deriveLicenseExpression(rows) {
    const missing = rows.filter((row) => !row.license);
    if (missing.length > 0) {
        throw new Error(`cppjs: cannot derive a license expression - rows without a license: ${missing.map((row) => row.name).join(', ')}`);
    }
    const parts = [...new Set(rows.map((row) => (/\s/.test(row.license) ? `(${row.license})` : row.license)))]
        .sort((a, b) => a.localeCompare(b));
    const expression = parts.join(' AND ');
    const { isValid, error } = validateSpdx(expression);
    if (!isValid) {
        throw new Error(`cppjs: derived license expression is not valid SPDX (${error}): ${expression}`);
    }
    return expression;
}

export function formatCycloneDxSbom(rows, target = {}) {
    return `${JSON.stringify({
        bomFormat: 'CycloneDX',
        specVersion: '1.5',
        version: 1,
        metadata: {
            component: {
                type: 'library',
                name: target.name || 'unknown',
                ...(target.version ? { version: target.version } : {}),
            },
        },
        components: [...rows]
            .sort((a, b) => a.name.localeCompare(b.name))
            .map((row) => ({
                type: 'library',
                name: row.name,
                ...(row.nativeVersion ? { version: row.nativeVersion } : {}),
                ...(row.nativeVersion ? { purl: `pkg:generic/${row.name}@${row.nativeVersion}` } : {}),
                ...(row.license ? { licenses: [{ expression: row.license }] } : {}),
                ...(row.sha256 ? { hashes: [{ alg: 'SHA-256', content: row.sha256 }] } : {}),
                ...(row.sourceUrl ? { externalReferences: [{ type: 'distribution', url: row.sourceUrl }] } : {}),
                ...(row.licenseSelected ? { properties: [{ name: 'cppjs:license-declared', value: row.licenseDeclared }] } : {}),
            })),
    }, null, 2)}\n`;
}
