import { describe, test, expect } from 'vitest';
import {
    validateBinConfig, renderBinJson, renderBinNpmignore, renderDispatcher,
    renderBinCommands, renderCommandStub,
} from '../src/utils/binTools.js';

const bin = (overrides = {}) => ({
    multicall: { linkTarget: 'gdal_app', sourcesDir: 'apps' },
    tools: {
        gdal: { kind: 'binary', publish: true },
        gdalinfo: { kind: 'multicall-entry', publish: true },
        ogr2ogr: { kind: 'multicall-entry', publish: true },
    },
    ...overrides,
});

describe('validateBinConfig', () => {
    test('splits binaries and multicall entries', () => {
        const result = validateBinConfig(bin());
        expect(result.binaries).toEqual(['gdal']);
        expect(result.multicall).toEqual(['gdalinfo', 'ogr2ogr']);
    });

    test('rejects an empty map', () => {
        expect(() => validateBinConfig({ tools: {} })).toThrow(/empty/);
    });

    test('rejects multicall entries without exactly one binary host', () => {
        expect(() => validateBinConfig(bin({
            tools: { gdalinfo: { kind: 'multicall-entry', publish: true } },
        }))).toThrow(/exactly one/);
    });
});

describe('renderBinJson', () => {
    test('round-trips the tool map', () => {
        const parsed = JSON.parse(renderBinJson(bin()));
        expect(Object.keys(parsed.tools)).toEqual(['gdal', 'gdalinfo', 'ogr2ogr']);
        expect(parsed.tools.gdalinfo.kind).toBe('multicall-entry');
    });
});

describe('renderBinNpmignore', () => {
    test('negates only publish:true tools under the bin wildcard', () => {
        const text = renderBinNpmignore(bin({
            tools: {
                gdal: { kind: 'binary', publish: true },
                gdalinfo: { kind: 'multicall-entry', publish: false },
            },
        }));
        expect(text).toContain('dist/prebuilt/**/bin/*');
        expect(text).toContain('!dist/prebuilt/**/bin/gdal');
        expect(text).not.toContain('!dist/prebuilt/**/bin/gdalinfo');
        expect(text.startsWith('# GENERATED by crossbind')).toBe(true);
    });
});

describe('renderBinCommands', () => {
    test('maps every published tool to a -wasi command', () => {
        expect(renderBinCommands(bin())).toEqual({
            'gdal-wasi': 'bin/gdal-wasi.mjs',
            'gdalinfo-wasi': 'bin/gdalinfo-wasi.mjs',
            'ogr2ogr-wasi': 'bin/ogr2ogr-wasi.mjs',
        });
    });

    test('skips publish:false tools', () => {
        const commands = renderBinCommands(bin({
            tools: {
                gdal: { kind: 'binary', publish: true },
                gdalinfo: { kind: 'multicall-entry', publish: false },
            },
        }));
        expect(Object.keys(commands)).toEqual(['gdal-wasi']);
    });

    test('honors the commands:false opt-out', () => {
        expect(renderBinCommands(bin({ commands: false }))).toEqual({});
    });
});

describe('renderCommandStub', () => {
    test('pins the tool at the call site over the crossbind runtime', () => {
        const stub = renderCommandStub('cs2cs');
        expect(stub.startsWith('#!/usr/bin/env node\n')).toBe(true);
        expect(stub).toContain("import { run } from 'crossbind/src/runtime/wasiRun.mjs';");
        expect(stub).toContain("await run(import.meta.url, 'cs2cs');");
    });
});

describe('renderDispatcher', () => {
    test('dispatches mapped tools and falls through to the binary host', () => {
        const source = renderDispatcher(bin());
        expect(source).toContain('int gdal_multicall_main(int, char**);');
        expect(source).toContain('if (!std::strcmp(tool, "gdalinfo")) return gdalinfo_multicall_main(argc - 1, argv + 1);');
        expect(source.trim().split('\n').at(-2)).toContain('return gdal_multicall_main(argc, argv);');
    });
});
