// App-local Rust surface: imported directly from App.tsx like a .h file. The toolchain
// synthesizes its bridge crate on import and links it into the app - no package needed.
pub struct Counter {
    total: i32,
}

impl Counter {
    pub fn new(start: i32) -> Self {
        Counter { total: start }
    }
    pub fn add(&mut self, n: i32) -> i32 {
        self.total += n;
        self.total
    }
    // &self on purpose: exercises the generated by-ref shim.
    pub fn total(&self) -> i32 {
        self.total
    }
}
