name: build linux
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .github/workflows/build-linux.yml
  pull_request:
    branches:
      - main
    paths:
      - packages/**
      - .github/workflows/build-linux.yml

permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 #v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build for Linux
        run: pnpm run ci:linux:build
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm run e2e:prod
