name: test core
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cppjs-core/cpp.js/**
      - .github/workflows/test-core.yml
  pull_request:
    branches:
      - main
    paths:
      - cppjs-core/cpp.js/**
      - .github/workflows/test-core.yml

permissions: {}
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 #v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Unit tests
        run: pnpm --filter cpp.js test
