name: test core
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cppjs-core/cpp.js/**
      - cppjs-packages/**
      - .github/workflows/test-core.yml
  pull_request:
    branches:
      - main
    paths:
      - cppjs-core/cpp.js/**
      - cppjs-packages/**
      - .github/workflows/test-core.yml

permissions: {}
jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 #v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Unit tests with coverage thresholds
        if: matrix.os == 'ubuntu-latest'
        run: pnpm --filter cpp.js test:coverage
      - name: Unit tests
        if: matrix.os == 'windows-latest'
        run: pnpm --filter cpp.js test
      - name: License SPDX check
        if: matrix.os == 'ubuntu-latest'
        working-directory: cppjs-samples/cppjs-playground-web-vanilla
        run: node ../../cppjs-core/cpp.js/src/bin.js licenses --check
